name: Deploy Widgetbook web

on:
  push:
    branches:
      - master
    paths:
        - 'widgetbook_example/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
        with:
          version: latest
          channel: stable
      - name: Install dependencies
        working-directory: widgetbook_example
        run: flutter pub get
      - name: Setup URL
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Build Widgetbook web
        run: make web
        env:
          FLUTTER_BASE_HREF: /${{ env.REPOSITORY_NAME }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'widgetbook_example/build/web'
      - uses: actions/deploy-pages@v4